### ISSUE TITLE
Apport and apport kde installed after upgrade

### ISSUE THREAD

**Issue by lucasrunner** [netrunner-kubuntu-legacy/netrunner-feedback#10]
Apport and apport kde  are installed after  system upgrade (kubuntu-notification-helper) Netrunner 12.12 beta 32 bit

**Comment by frgaudet** [comment]
You mean KNH has dependency against apport & apport-kde ? 

I re-packaged KNH and removed those, so I'm suprised you installed apport due to KNH. Could you check the origin of this package ?

**Comment by lucasrunner** [comment]
Origin: Ubuntu
Component: main
kubuntu-notification-helper (12.10ubuntu3) quantal

There is also 11.10ubuntu1-1netrunner1 package, so I think that you should bump package version ;)

**Comment by frgaudet** [comment]
No need , it's a pinned package

**Comment by lucasrunner** [comment]
Well after upgrade beta 2, apport is still installed, also for some unknown reason Muon was removed. Here is log from /var/log/apt/history.log http://wklej.org/id/893963/ From what I see few more packages were also removed

**Comment by lucasrunner** [comment]
fixed
