### ISSUE TITLE
Update unable to get downloads

### ISSUE THREAD

**Issue by austinfergie** [netrunner-kubuntu-legacy/netrunner-feedback#12]

**Comment by frgaudet** [comment]
Hi @austinfergie 

What's the error printed ?

**Comment by lucasrunner** [comment]
ekhm
http://wklej.org/id/874763/

**Comment by frgaudet** [comment]
Ok. There a hosting issue about netrunner-os.com, we hope everything will come back soon. Sorry for the inconvenience.

**Comment by star-buck** [comment]
solved.
