### ISSUE TITLE
Include KDE 4.9.3 in Final to overcome Kubuntu bug 1061073

### ISSUE THREAD

**Issue by sez11a** [netrunner-kubuntu-legacy/netrunner-feedback#16]
There was a bug in KDE 4.9.2 that created desktop artifacts and severe slowdown when used in combination with Mesa 9. The bug was fixed in KDE 4.9.3 and forward. Since 4.9.3 is now in the Kubuntu stable repository, it would be best to include it by default in the Netrunner 12.12 installation. 

See https://bugs.launchpad.net/ubuntu/+source/mesa/+bug/1061073 for further information.

**Comment by star-buck** [comment]
done
