### ISSUE TITLE
WebAccounts requires to have access to bug

### ISSUE THREAD

**Issue by ghost** [netrunner-kubuntu-legacy/netrunner-feedback#18]
When running WebAccounts, trying to setup one or more Web accounts throws following error - see attached. The corresponding system message is: kcmshell(4863)/kdeui (Wallet): Couldn't start kwalletd:  "Could not find service 'kwalletd.desktop'." 

![webaccounts-bug](https://f.cloud.github.com/assets/3050291/14947/636c7766-46c8-11e2-9784-3159ea09be27.png)

How to fix:
Run kwalletd from command line, after that the applet starts fine.

However, the message itself remains ambiguous - incomplete string after "have access to".

Regards,
Dedoimedo

**Comment by star-buck** [comment]
notified KDE developer (closed for upstream)
