### ISSUE TITLE
Installer crashes in partitioning setup stage

### ISSUE THREAD

**Issue by ghost** [netrunner-kubuntu-legacy/netrunner-feedback#19]
Sometimes accompanied by desktop plasma crash.
No trace available from the command line.

/var/log/syslog reports segfault in Python - after not finding /dev/sdb6.

Dec 15 15:04:39 netrunner ubiquity[5109]: Device /dev/sdb6 not found in os-prober output
Dec 15 15:04:39 netrunner ubiquity[5109]: Device /dev/sda6 not found in os-prober output
Dec 15 15:05:09 netrunner ubiquity[5109]: switched to page Form
Dec 15 15:05:34  ubiquity[5109]: last message repeated 4 times
Dec 15 15:05:34 netrunner kernel: [ 1036.396477] ubiquity[5109]: segfault at 120 ip 000000000047dc99 sp 00007fff11ebc2b0 error 6 in python2.7[400000+21f000]

I could retry with debug symbols installed.

The disk layout is as follows:

root@netrunner:~# fdisk -l

Disk /dev/sda: 40.0 GB, 40020664320 bytes
255 heads, 63 sectors/track, 4865 cylinders, total 78165360 sectors
Units = sectors of 1 \* 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disk identifier: 0x000bba46

   Device Boot      Start         End      Blocks   Id  System
/dev/sda1   \*        2048    20482047    10240000   83  Linux
/dev/sda2        20482048    40962047    10240000   83  Linux
/dev/sda3        40964094    78163967    18599937    5  Extended
/dev/sda5        40964096    45158399     2097152   82  Linux swap / Solaris
/dev/sda6        45160448    78163967    16501760   83  Linux

Disk /dev/sdb: 40.0 GB, 40020664320 bytes
255 heads, 63 sectors/track, 4865 cylinders, total 78165360 sectors
Units = sectors of 1 \* 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disk identifier: 0x00031620

   Device Boot      Start         End      Blocks   Id  System
/dev/sdb1   \*        2048    20482047    10240000   83  Linux
/dev/sdb2        20482048    40962047    10240000   83  Linux
/dev/sdb3        40964094    78163967    18599937    5  Extended
/dev/sdb5        40964096    45158399     2097152   82  Linux swap / Solaris
/dev/sdb6        45160448    78163967    16501760   83  Linux

Disk /dev/sdc: 16.0 GB, 16030597120 bytes
255 heads, 63 sectors/track, 1948 cylinders, total 31309760 sectors
Units = sectors of 1 \* 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disk identifier: 0x0002c058

Regards,
Dedoimedo

**Comment by Fisiu** [comment]
Do You have RAID setup (aka fakeraid)? If so, make sure dmraid is installed and activated (`dmraid -ay`) before installation starts.

**Comment by ghost** [comment]
No, I do not have any RAID setup. Moreover, even if I did - assuming some arbitrary user, the setup needs to properly configure and activate the RAID setup.

Regards,
Dedoimedo

**Comment by mehor** [comment]
Did you touch (literally) swap partition during the setup? It seems that this might be a problem on some machines and it's the issue present in couple of Ubuntu-based distros. Not sure if this is the same issue as yours, but here's the link to the bug report I've stumbled upon earlier: https://bugs.launchpad.net/ubuntu/+source/ubiquity/+bug/1038522

**Comment by ghost** [comment]
Nope. I left the system do its own magic.
The live session did turn the swap on both the swap partitions.
But then, there were no bugs when testing Kubuntu.
I'll try the official release and see what gives.

Dedoimedo

**Comment by ghost** [comment]
A review of 12.12 mentioned that the installer fails when attempting to set up a separate home partition, and I experienced this problem, too. Perhaps it's related to the issue here? If not, I can open a new issue.
