### ISSUE TITLE
Esc shortcut in Yakuake conflicts with Vim

### ISSUE THREAD

**Issue by sez11a** [netrunner-kubuntu-legacy/netrunner-feedback#2]
In Netrunner, the Ctrl+Shift+S shortcut to close a terminal session has been replaced with Esc. This conflicts with vim, as the Esc key is used to switch from Insert mode back to Command mode. Since it is highly likely that people will be using vim in the terminal, this shortcut should be set back to its (admittedly non-intuitive) default.

**Comment by star-buck** [comment]
Confirmed and will be fixed in final version.

Solution:
Reset all shortcuts under Yakuake - Configure: Shortcuts to default.
