### ISSUE TITLE
A click on URL in Muon Discoverer, KDE Telapathy etc. opens a new Firefox window each time

### ISSUE THREAD

**Issue by TheRealPTR** [netrunner-kubuntu-legacy/netrunner-feedback#20]
A click on URL in Muon Discoverer, KDE Telapathy etc. opens a new Firefox window each time, instead of just a new tab. Also Dropbox when clicked "Lounch Dropbox Website" opens a new Konqueror window instead of a Firefox's tab.

**Comment by star-buck** [comment]
fixed
