### ISSUE TITLE
Audio buttons don't work properly with Tomahawk

### ISSUE THREAD

**Issue by TheRealPTR** [netrunner-kubuntu-legacy/netrunner-feedback#21]
I have Dell Inspiron 1525 with four audio buttons. Tomahawk reacts to pressing them only when it is set to be the active window. When focus in on a different window and/or Tomahawk is send to Sys Tray buttons have no effect. Clementine installed from the Netrunner's repos does not react at all (though the key shortcuts are set correctly in Clementine). But Clementine installed from the developmental PPA works fine :-/

**Comment by star-buck** [comment]
Clementine and Tomahawk should be from Kubuntus repo, so it is very likely upstream.

**Comment by TheRealPTR** [comment]
Might be... This problem occurred in Kubuntu 12.04 as well:
 http://code.google.com/p/clementine-player/issues/detail?id=2908
