### ISSUE TITLE
Webaccounts creates KMail accounts, but Thunderbird is set as default email client

### ISSUE THREAD

**Issue by sez11a** [netrunner-kubuntu-legacy/netrunner-feedback#3]
Recommendation: remove Thunderbird as the default, or remove it altogether and let users install it if they want to use it.

**Comment by star-buck** [comment]
Thunderbird is currently much more standard than Kmail, with Kmail/KDE PIM still having issues, so after KDE PIM/Kmail will get another boost of developer attention in 13.06/13.12, we will then think to replace Thunderbird.

**Comment by sez11a** [comment]
Okay; but please be aware that Thunderbird currently has problems too, that aren't yet fixed in updates: 

https://bugzilla.mozilla.org/show_bug.cgi?id=803843
https://bugzilla.mozilla.org/show_bug.cgi?id=806760

I'm currently using KMail and all the akonadi issues are gone with the 4.9.x release.
