### ISSUE TITLE
Kickoff Launcher: Favorites tab

### ISSUE THREAD

**Issue by mehor** [netrunner-kubuntu-legacy/netrunner-feedback#5]
1. Since Kontact contains only the Addressbook and Calendar, maybe it shouldn't be in the <i>Favorites</i> tab at all. It's just too crippled. Probably replace it with Thunderbird, since it is the default email/PIM application.
2. Amarok isn't installed by default, so the shortcut to it shouldn't be in the <i>Favorites</i>. Tomahawk instead?
3. konqbrowser should probably be replaced with Firefox, the default browser.

**Comment by star-buck** [comment]
1. we could place thunderbird also there
2. yes
3. yes, konqbrowser should be removed from favorites and firefox added
