### ISSUE TITLE
Kickoff Launcher: Applications tab

### ISSUE THREAD

**Issue by mehor** [netrunner-kubuntu-legacy/netrunner-feedback#6]
1. Virtual Machine (Vbox) should probably go into the <i>System</i> menu.
2. Synaptic Package Manager should be removed from <i>Settings</i> menu, it's already in <i>System</i>.
3. Remove Karbon from <i>Graphics</i> menu, since it isn't installed. Or, alternatively, make it installed by default.

**Comment by star-buck** [comment]
1. is placed there on purpose for easy spotting it.
2. confirmed
3. true
