### ISSUE TITLE
Restore default panel (solution)

### ISSUE THREAD

**Issue by lucasrunner** [netrunner-kubuntu-legacy/netrunner-feedback#7]
There is no easy way to restore  default "netrunner panel", so I played a bit with http://techbase.kde.org/KDE_System_Administration/PlasmaDesktopScripting and created script which restores "similar" panel

How to try:

Open krunner and run "desktop console" or "qdbus org.kde.plasma-desktop /MainApplication showInteractiveConsole",  paste this script
http://wklej.org/id/871213/ and click execute

If we want to make this permanently, replace content of layout.js in /usr/share/kde4/apps/plasma/layout-templates/org.kde.plasma-desktop.defaultPanel/contents/ with script from link.
Next time when user choose "Add panel – default panel" will see this 
http://s4.ifotos.pl/img/panelpng_xnnnrxh.png
Krunner icon is missing because it is a little bit tricky to add to panel (no krunner.desktop file) 

Work based on
http://kde-apps.org/content/show.php?content=147589

**Comment by star-buck** [comment]
Awesome work!

I have started to experiment with scripting myself and will definately give
this a spin for taking it further to perfection (like setting the
taskmanager behaviour, systray settings, etc. if possible).

Feel free to refine this yourself and post updates here!
Am 15.11.2012 00:31 schrieb "lucasrunner" notifications@github.com:

**Comment by frgaudet** [comment]
Nice touch lucasrunner ! We'll definitly give it a try :)

Starbuck : I already spinned and uploaded beta2 ISO, but I test it this solution right now for the next ISO.

**Comment by lucasrunner** [comment]
Setting taskmanager behavior and systray settings should be quite easy, I will update script tonight

**Comment by frgaudet** [comment]
Based on your work , here is a new script :

http://paste.kde.org/607154

The only thing I couldn't make it work are the internal_spacers which are expendable by default, no way to specify a size

**Comment by lucasrunner** [comment]
Thanks @wavespot
Added task manger specific options, removed spacers
http://wklej.org/id/871930/

I think that script is now almost complete ;)

**Comment by frgaudet** [comment]
thanks @lucasrunner 

I also added all clock settings, I'll spin a new ISO and see what happening

**Comment by lucasrunner** [comment]
Any progress on this? May I help with something?

**Comment by star-buck** [comment]
should also be fixed in RC.

**Comment by lucasrunner** [comment]
fixed, thanks
