### ISSUE TITLE
Text in shutdown dialog is cut

### ISSUE THREAD

**Issue by lucasrunner** [netrunner-kubuntu-legacy/netrunner-feedback#8]
First I must say I really like new default plasma theme, but I found one thing that can be improved:

Text in shutdown dialog is cut as seen on the picture 

http://s6.ifotos.pl/img/shutdownp_xnnnarx.png

Netrunner 12.12 beta 32 bit

**Comment by lucasrunner** [comment]
Ok, it seems that after rewrite shutdown dialog to qml, some themes have this problem. So I have replaced  shutdowndialog.svg from naked theme, with shutdowndialog.svgz form united theme http://kde-look.org/content/show.php/United?content=150862.  Now it looks like this http://s4.ifotos.pl/img/dialgpng_xnnaxnp.png
Updated naked theme http://www.sendspace.com/file/66d6lj

**Comment by lucasrunner** [comment]
Issue still exist in Netrunner 12.12 beta 2

**Comment by star-buck** [comment]
is going to be fixed in final, we are testing solution, so RC still has it.

**Comment by lucasrunner** [comment]
Fixed in rc
