### ISSUE TITLE
Window decoration issues

### ISSUE THREAD

**Issue by lucasrunner** [netrunner-kubuntu-legacy/netrunner-feedback#9]
I found 2 issues with default window decoration:
1. Buttons (minimize, close etc) are not visible on inactive windows. This is quite annoying especially if we have few windows open, as it is hard to hit the right button.
   http://s4.ifotos.pl/img/window1pn_xnnnann.png
2. There is not possible to resize window from left and right side, so we can't change width of application. See this for example http://s6.ifotos.pl/img/muonpng_xnnaxwx.png. There is no way to change muon width. Possibility to change width of application is really important for people with low screen resolution. And this is regression compared to Netrunner 4.2.1

Netrunner 12.12 beta 32 bit

**Comment by star-buck** [comment]
We will likely switch to Metro Dark for Window Theme in Final.

**Comment by lucasrunner** [comment]
If I may suggest
http://www.netrunner-os.com/forums/ideas/forman-as-default-window-decoration-for-netrunner-12-12/#p1246

**Comment by star-buck** [comment]
will give it a look

**Comment by lucasrunner** [comment]
Issue still exist in Netrunner 12.12 beta 2

**Comment by star-buck** [comment]
is fixed in RC.

**Comment by lucasrunner** [comment]
Where can I download this rc?

**Comment by star-buck** [comment]
right here:
http://54.246.99.126/test/

we are currently trying to apply infinality patches for a better font rendering on small scale, as KDE still lacks somewhat compared to Ubuntu or GTK3:
http://www.infinality.net/blog/

If you happen to find out any working setup, we would love to make it default before we release 12.12!

**Comment by lucasrunner** [comment]
1. Buttons are now visible but title of inactive window is not.
   http://s4.ifotos.pl/img/snapshot1_xewrhra.png
2.  Still not fixed

Btw font rendering in Netrunner is perfect for me ;)

**Comment by star-buck** [comment]
yes, color scheme 44 needs to be applied, it just is listed as active.
try to see if it works selecting some other color scheme and then reselct Netrunner 44.

**Comment by lucasrunner** [comment]
May I ask what is wrong with FormaN? Just curious ;). It appears as I'm not the only one who likes FormaN :)
http://www.netrunner-os.com/forums/ideas/forman-as-default-window-decoration-for-netrunner-12-12/#p1246
I will try another color scheme but what with issue number 2? It is even more problematic

**Comment by star-buck** [comment]
Nothings wrong, just we want to transform away from the win7 feel to a more
flat style.
Am 11.12.2012 22:09 schrieb "lucasrunner" notifications@github.com:

**Comment by lucasrunner** [comment]
I fully support the idea of giving Netrunner a unique look. I am also very well aware that there have been quite a few accusations of copying Windows. The thing is, no matter what we do, KDE will always be compared to Windows and reassemble it in a certain way, be it even for the fact that it has a single panel at the bottom of the screen.But what is worth keeping in mind is what the users want, and choosing the window decoration could a first step on the road of direct implementing their suggestions. What about a poll on the forum, where Netrunner users would be able to vote between a few options selected by the developers?

FornaN is a solid alternative due to the transparency-fits-everything aspect and simply good looks. The above is of course only what I personally think and I will respect any decision made by the Netrunner team.
Of course the lack of ability to resize windows still exists (aka issue number 2)

**Comment by lucasrunner** [comment]
Ok, after some searching I found a way to resize windows (issue number 2). System Settings>Workspace Appearance> Window Decorations> QtCurve> Configure Decoration>Border Size> Tiny. Hope to see this fixed in final ;)

**Comment by star-buck** [comment]
FormaN used.
